name: Build and Push LaTeX PDF to This and Another Repo

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: Rename output
        run: mv main.pdf resume.pdf

      # Commit resume.pdf to THIS repository
      - name: Commit PDF to this repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add resume.pdf
          git commit -m "Workflow - Update resume.pdf" || echo "No changes to commit"
          git push

      # Push resume.pdf to ANOTHER repository
      - name: Push PDF to website repo
        run: |
          git clone https://x-access-token:${{ secrets.TARGET_REPO_PAT }}@github.com/tavignesh/vigneshta.com.git
          cd vigneshta.com
          cp ../resume.pdf ./
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add resume.pdf
          git commit -m "Update resume.pdf from Workflow" || echo "No changes to commit"
          git push
